version: "3.8"
services:
    db_5_7_38:
        image: mysql:5.7.38
        container_name: "mysql-5.7.38-docker"
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode=''
        ports:
            - "5738:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=TjsDgwGPz5ANbJUU
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 2s
            timeout: 5s
            retries: 30
    db_5_5_53:
        image: mysql:5.5.53
        container_name: "mysql-5.5.53-docker"
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode=''
        ports:
            - "5553:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=TjsDgwGPz5ANbJUU
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 2s
            timeout: 5s
            retries: 30